PetAdoptions/petsite/Controllers/PetListAdoptionsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using PetSite.Models;
using Amazon.XRay.Recorder.Handlers.AwsSdk;
using System.Net.Http;
using Amazon.XRay.Recorder.Handlers.System.Net;
using Amazon.XRay.Recorder.Core;
using System.Text.Json;
using PetSite.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;

namespace PetSite.Controllers
{
    public class PetListAdoptionsController : Controller
    {
        private static HttpClient _httpClient;
        private IConfiguration _configuration;

        public PetListAdoptionsController(IConfiguration configuration)
        {
            _configuration = configuration;
            AWSSDKHandler.RegisterXRayForAllServices();

            _httpClient = new HttpClient(new HttpClientXRayTracingHandler(new HttpClientHandler()));
        }

        // GET
        public async Task<IActionResult> Index()
        {
            AWSXRayRecorder.Instance.BeginSubsegment("Calling PetListAdoptions");
            
            Console.WriteLine($"[{AWSXRayRecorder.Instance.GetEntity().TraceId}][{AWSXRayRecorder.Instance.TraceContext.GetEntity().RootSegment.TraceId}] - Calling PetListAdoptions API");

            string result;

            List<Pet> Pets = new List<Pet>();

            try
            {
                //string petlistadoptionsurl = _configuration["petlistadoptionsurl"];
                string petlistadoptionsurl = SystemsManagerConfigurationProviderWithReloadExtensions.GetConfiguration(_configuration,"petlistadoptionsurl");
                
        
                result = await _httpClient.GetStringAsync($"{petlistadoptionsurl}");
                Pets = JsonSerializer.Deserialize<List<Pet>>(result);
            }
            catch (Exception e)
            {
                AWSXRayRecorder.Instance.AddException(e);
                throw e;
            }
            finally
            {
                AWSXRayRecorder.Instance.EndSubsegment();
            }

            return View(Pets);
        }
    }
}

PetAdoptions/petsite/Views/Shared/_AdoptionItem.cshtml
@using Microsoft.CodeAnalysis.CSharp.Syntax
@model Pet;
    
        <img class="pet-thumbnail" src="@Model.peturl" />
        
        <div class="pet-name">
            <span>@Model.pettype-@Model.petcolor</span>
        </div>
        <div class="pet-price">
            <span>@Model.price</span>
        </div>
        <div class="pet-list-item">
            <span>Adoption Id-@Model.transactionid</span>
        </div>
        <div class="pet-list-item">
            <span>Adopted on-@Model.adoptiondate</span>
        </div>

PetAdoptions/petsite/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Html
@using Amazon.SimpleSystemsManagement
@using Amazon.SimpleSystemsManagement.Model


<!DOCTYPE html>
<html lang="en">
<head>
    @(new HtmlString(new AmazonSimpleSystemsManagementClient().GetParameterAsync(new GetParameterRequest() { Name = "/petstore/rumscript" }).Result.Parameter.Value))
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Observability PetAdoptions</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
    <link rel="stylesheet" href="~/css/petstyles.css"/>
</head>
<body>
<div class="pet-wrapper">
    <header class="pet-header">

        <div class="container">
            <article class="row">

                <section class="col-lg-7 col-md-6 col-xs-12 align-self-center">
                    <a asp-controller="home" asp-action="index">
                        <img src="~/images/brand.png" alt="Petadoption"/>
                    </a>
                </section>
                <section class="col-md-2 align-self-center">
                    <a asp-controller="PetListAdoptions" asp-action="index" id="seeadoptionlist" style="color: #7abaff">
                        See Adoption List
                    </a>
                </section>

                <section class="col-md-3 align-self-center">
                    <a asp-controller="Home" asp-action="HouseKeeping" id="performhousekeeping" style="color: #7abaff">
                        Perform Housekeeping
                    </a>
                </section>
            </article>

        </div>
    </header>
    @RenderBody()


</div>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@RenderSection("Scripts", required: false)
</body>
</html>